FROM golang:1.17.1 as builder
WORKDIR /app
COPY client /app/client
COPY hello /app/hello
COPY go.mod /app
COPY go.sum /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./client

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/app .
CMD ["./app"]
