FROM golang:1.17.1 as builder
WORKDIR /app
COPY batch_client /app/batch_client
COPY batch_processor /app/batch_processor
COPY go.mod /app
COPY go.sum /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o batch_client ./batch_client

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/batch_client .
CMD ["./batch_client"]
